apiVersion: 1

datasources:
  # configure a default loki datasource 
  - name: loki
    uid: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true

  - name: mimir
    uid: mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
